root: '123456'
bt_uin: '1000000000'
enable_webui_interaction: false
debug: false
github_proxy: null
check_ncatbot_update: true
skip_ncatbot_install_check: false
websocket_timeout: 15
napcat:
  ws_uri: ws://[::1]:3000
  ws_token: your_ws_token
  ws_listen_ip: ::1
  webui_uri: http://localhost:6099
  webui_token: your_webui_token
  enable_webui: true
  check_napcat_update: false
  stop_napcat: false
  remote_mode: false
  report_self_message: false
  report_forward_message_detail: true
plugin:
  plugins_dir: E:\.ncatbot_plugins_runtime
  plugin_whitelist:
  - bot
  plugin_blacklist: []
  skip_plugin_load: false
